### ISSUE TITLE
Namespace and Kubeflow Profile disconnect after Kubeflow 1.6 upgrade

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/kubeflow#114]
/kind bug

**What happened:**
When I log in to Kubeflow Dev after the upgrade (using my cloud account), I am told to create a new profile. I am not able to log in to my existing Kubeflow profile. If I try, it gives me an error. I am however able to create a new profile and log in.

**Screenshot:**
![image](https://user-images.githubusercontent.com/8212170/195906522-5a7a2054-0334-443a-917f-bde6e67dc66c.png)

**Comment by Souheil-Yazji** [comment]
stale
