### ISSUE TITLE
[Frontend] Namespace drop down fails to populate

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/kubeflow#118]
/kind bug

**What steps did you take and what happened:**
Simply open kubeflow-dev
![image](https://user-images.githubusercontent.com/35379392/198712168-ced07fef-55a3-4d48-8987-0ca378e10f8e.png)
![image](https://user-images.githubusercontent.com/35379392/198712455-e79c165f-10fd-4af3-92b7-ff88a5c5f2e5.png)

no namespaces appear

**What did you expect to happen:**
Namespaces should appear in the drop down menu, and it should be clickable.

**Anything else you would like to add:**
Modifying the URL to access another namespace reloads the page correctly but does not change namespaces. 

**Environment:**

- Kubeflow version: 1.6
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`): AKS 
- Kubernetes version: (use `kubectl version`): 1.22
- OS (e.g. from `/etc/os-release`):

**Comment by chuckbelisle** [comment]
See network tab when debugging

**Comment by mathis-marcotte** [comment]
I can't seem to reproduce the bug effectively. Although it seems to possibly happen after a certain amount of inactivity. So it might be a session timeout thing.

**Comment by mathis-marcotte** [comment]
After looking at the network tab, it seems that the error is caused by this request failing(the other 4 failed request are also happening when this bug isn't present)
![image](https://user-images.githubusercontent.com/84033116/199713612-3b10f9b6-af42-4a75-807a-e6af98ff4c4b.png)

**Comment by mathis-marcotte** [comment]
Response body isn't really helpful : `{"error":{}}`

**Comment by mathis-marcotte** [comment]
In the centraldashboard logs in ArgoCD, we see these error messages which seem to be caused by the bug
![image](https://user-images.githubusercontent.com/84033116/199759012-92a0427a-eae3-4b27-bdeb-ca7b4ed4e42c.png)

**Comment by mathis-marcotte** [comment]
Upon further investigation after printing out that entire error object instead of [object Object], I noticed that this seems to come from "/v1/bindings" when trying to read the bindings for the logged in user

**Comment by mathis-marcotte** [comment]
I don't know if this is a cause or a coincidence but it's noteworthy. It seems that when this request fails(always seems to be a 403 error), the query search params in the uri refers to the user value( `?user=mathis.marcotte%40cloud.statcan.ca` ). But, when this request is succesful, the query search params in the uri refer to the namespace value( `?namespace=mathis-marcotte` )

**Comment by mathis-marcotte** [comment]
There doesn't appear to be a difference in the request object between a successful request and a failed one. These requests send the username value as a query parameter, and for the failed request the error code seems to always be 403(Forbidden).

This appears to be where the error is being returned (in components/access-management/kfam/api_default.go):
![image](https://user-images.githubusercontent.com/84033116/199985919-826af5a8-96d3-4c22-bfd1-79dc1f9d1a84.png)

**Comment by mathis-marcotte** [comment]
With that 403 response, it was also noting "Unexpected EOF {}" in the message returned.

**Comment by Collinbrown95** [comment]
CC @Souheil-Yazji @mathis-marcotte 

We determined that the error sporadically happens when the `profiles-deployment` pod attempts to list profiles by sending an API call to the Kubernetes API server.

The only information we can gather from the upstream code is that the error has something to do with an unexpected EOF.

We were not able to reproduce the error locally on a k3d cluster (every attempt was successful in our local environment).

In order to get more information about the error, we need to deploy our own custom version of the upstream kfam image where we insert debug logs to provide more information around the error. This would require several more hours of work, so we are putting this on pause until the priority of this ticket increases.

**Comment by mathis-marcotte** [comment]
Pasting these. This is what the typical request and response when the error gets triggered(tested locally).
```
Request:  {
  "method":"GET",
  "qs":{},
  "headers":{},
  "uri":"http://localhost:8081/kfam/v1/bindings",
  "useQuerystring":false,
  "json":true
}
Response:  {
  "statusCode":403,
  "body":"Get \"https://10.131.0.1:443/apis/kubeflow.org/v1beta1/profiles\": unexpected EOF{}",
  "headers":{
    "content-type":"application/json; charset=UTF-8",
    "date":"Wed, 23 Nov 2022 15:46:17 GMT",
    "content-length":"81","connection":"close"
  },
  "request":{
    "uri":{
      "protocol":"http:",
      "slashes":true,
      "auth":null,
      "host":"localhost:8081",
      "port":"8081",
      "hostname":"localhost",
      "hash":null,
      "search":null,
      "query":null,
      "pathname":"/kfam/v1/bindings",
      "path":"/kfam/v1/bindings",
      "href":"http://localhost:8081/kfam/v1/bindings"
    },
    "method":"GET",
    "headers":{
      "accept":"application/json"
    }
  }
}
```

**Comment by chuckbelisle** [comment]
Let's park this ticket in our backlog for now. User can be asked to refresh their page when this behaviour is met

**Comment by mathis-marcotte** [comment]
@chuckbelisle I was going to use this ticket to implement the mitigation patch I had mentioned. Should that be a new ticket then?

**Comment by Souheil-Yazji** [comment]
Thanks to @mathis-marcotte, a patch was released (https://github.com/StatCan/daaas/issues/1464) to mitigate this bug. Will close issue for now.

I'm not sure how points assignment would work for this, so I will close it with no assignees.
