### ISSUE TITLE
Notebook Servers view has 404 for direct (browser) HTTP requests

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow#12]
I think this is a regression, but the button no longer works

![Screenshot from 2020-08-13 11-35-19](https://user-images.githubusercontent.com/10801138/90156286-41441f00-dd5a-11ea-9936-54e9defe3d2d.png)

**Comment by brendangadd** [comment]
Re-opening: need PR(s) that fix this issue linked so we know what fixed it. /cc @zachomedia

**Comment by zachomedia** [comment]
This is fixed by: https://github.com/StatCan/jupyter-apis/commit/c6280e40c11618c3908449d92f2f67d4e6b17ecc
