### ISSUE TITLE
Virtual local Kubeflow dev environment

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow#15]
Relating to https://github.com/StatCan/jupyter-apis/issues/8 it would be good to set up a virtual, standardized, easy to reproduce and update local development environment for Kubeflow, such as a configuration for an Azure VM. 

I have not had success with minikf on D4s v3 RHEL7, WSL2 Ubuntu, or Win10 (though it remains possible that the Win10 failure was a space issue, if that needs more than 50GB, and part of this issue could be confirming that).

I have had success with minikf on a personal Ubuntu-based machine comparable in specs to a D4s v3 (but it remains possible that, for whatever reason, an Azure VM would need more). Ubuntu is not presently a standard internal workstation environment so there would be some extra work coming up with an automated configuration for it. I briefly looked into the Sprinkle project, and that could be useful, although it is designed for RHEL7 by default.

**Comment by blairdrummond** [comment]
Replacing this size with `Nil` as I think we're going to replace it with this issue: https://github.com/StatCan/daaas/issues/578

**Comment by blairdrummond** [comment]
Will close this. Argoflow resolves this as soon as the Ubuntu VMs on the cloud become available
