### ISSUE TITLE
Logout button not working after kubeflow 1.7 update

### ISSUE THREAD

**Issue by mathis-marcotte** [StatCan/kubeflow#152]
After doing the update to kubeflow 1.7, the logout button found in central dashboard does nothing when clicking on it. 

![image](https://github.com/StatCan/kubeflow/assets/84033116/b358dd56-a0b3-4658-b87d-bdb4a18c953b)

It does seem to be trying to do something, but the calls are failing.

**Comment by chuckbelisle** [comment]
Could we redirect users once they logout to https://www.statcan.gc.ca/data-analytics-services/aaw ?

**Comment by mathis-marcotte** [comment]
Seems like in the 1.7 update, upstream changed the logout button to take it's href value from an env variable instead of just having it written in the html. And then the default value they set for that env variable was `/authservice/logout`, while we expect just `/logout`. 

Another thing is that they switched from an anchor element (a) to a `<paper-button>` with an `<iron-ajax>`  for the definition of the logout button. This is also causing the logout to fail.

Reverting the button to how it used to be seems to fix the button.

**Comment by mathis-marcotte** [comment]
Changing the redirect URL, I get this error:
![image](https://github.com/StatCan/kubeflow/assets/84033116/8833fdd7-8e19-45e8-82fd-2be98874fde1)

Looking at the app registration in AAD, it does appear like we just need to add this new redirect URL to this list for it to work, however that can be done.
![image](https://github.com/StatCan/kubeflow/assets/84033116/3077f595-b842-460c-8820-f1af5cb6a6b0)

**Comment by mathis-marcotte** [comment]
Created ticket https://jirab.statcan.ca/browse/CLOUD-20035 to get the new URI added to dev and prod application registrations in AAD

**Comment by mathis-marcotte** [comment]
To make the logout redirect to the desired URL that we wanted, I was looking at the configmap for our "oidc-authservice" application. There was a `REDIRECT_URL` in that configmap that seemed to be want I needed to change upon first glance.

But, after testing by replacing the value we had for that parameter with the URL we wanted, it wasn't working as expected. And after confirming by reading the docs of our [oidc service](https://github.com/arrikto/oidc-authservice/tree/master) , that redirect_url is actually to specify where to send the oidc authorization code. Basically, kubeflow was redirecting to the specified url after a successful sign-in, which is not what we wanted.

Next step is to test the `AFTER_LOGOUT_URL` param from oidc-authservice, or possibly look at what the microsoft authentication service [suggests](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request)

**Comment by mathis-marcotte** [comment]
Tried `AFTER_LOGOUT_URL` and it didn't seem to do anything. So I also tried `STATIC_DESTINATION_URL` which is the old name, and that did something but the result seemed to behave similarly to `REDIRECT_URL`, which made the app navigate to the portal after choosing an account to log in with. And these do not behave like we expect/want, so we won't be switching that url and just keep it like it used to.

**Comment by mathis-marcotte** [comment]
I decided to look into why the new logout button that came with v1.7 wasn't working, so that we can possibly avoid more differences with upstream.

The issue seems to be that the Authorization header is not being set properly, which would probbably explain the error 403. It's trying to set the Authorization header by using the `authservice_session` cookie's value. But, it seems like the javascript can't get that cookie's value. I'm not 100% sure why, but it might be because of some `sameSite` rules, or because our app is running in https.

Either way, reverting to how it used to be done seems to be the best solution. Plus, it seems like with 1.7 they made the logout button into an button used to run an ajax request. That honestly seems odd to me to have the logout call be asynchronous.
