### ISSUE TITLE
Tests are failing for centraldashboard

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#20]
Two centraldashboard tests fail, which prevents the image from building. Need to fix them (or what's broken).

This issue is blocker priority because it stops security fixes from hitting prod.

**Comment by wg102** [comment]
This is the current information I gathered:

- The two errors are unhandled promises for the following tests:
https://github.com/StatCan/kubeflow/blob/7ad8eaf6bc5b99f8ef808a191773f71d08023c5b/components/centraldashboard/public/components/manage-users-view_test.js#L127 and https://github.com/StatCan/kubeflow/blob/7ad8eaf6bc5b99f8ef808a191773f71d08023c5b/components/centraldashboard/public/components/registration-page_test.js#L156 
- The last working commit was [7f40cf4 ](https://github.com/StatCan/kubeflow/commit/7f40cf4ee5968738be45cf0c40a98ace54beb237)
- The only changes in the next commit are related to updating packages.json, therefore I suspect a packet update (most likely the ones related to karma/jasmine) to have changed something.
- If the lines ` await yieldForRequests();` are removed, the tests do not show the unhandled promises anymore, but do not give the expected result either.
- I was looking into using a try/catch statement on this method, or some solution similar to that.
https://github.com/StatCan/kubeflow/blob/7ad8eaf6bc5b99f8ef808a191773f71d08023c5b/components/centraldashboard/public/ajax_test_helper.js#L36
