### ISSUE TITLE
Link to our own support materials on home page

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#22]
The home page has a bunch of documentation links, mostly about setting up Kubeflow itself.

![image](https://user-images.githubusercontent.com/2147814/92950864-6e542200-f42b-11ea-9043-0b221d04641a.png)

This is not useful information for our analysts. Let's replace most of those links with refs to our own end-user support materials. Maybe something like:

* [Advanced Analytics Workspace Docs](https://statcan.github.io/daaas/)
* [Video Tutorial Series](https://www.youtube.com/playlist?list=PL1zlA2D7AHugkDdiyeUHWOKGKUd3MB_nD)
* [Community Chat](http://statcan-aaw.slack.com/)
* [Official Kubeflow Docs](https://www.kubeflow.org/docs/)

![image](https://user-images.githubusercontent.com/2147814/92952429-f2a7a480-f42d-11ea-8ed1-a98f9eb5921c.png)

**Comment by Ito-Matsuda** [comment]
Looks like a simple cut and replace in [dashboard-view](https://github.com/StatCan/kubeflow/blob/stc-master/components/centraldashboard/public/components/dashboard-view.js)

Just need to learn how to build and view the changes
