### ISSUE TITLE
compare centraldashboard changes up until v1.2

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow#33]
Issue to track down which changes and new features were made to the centraldashboard component up until the v1.2 release. Tracking both upstream and our changes in this issue.

**Comment by wg102** [comment]
Central Dashboard: 
Sep 1 ci: Build/push centraldashboard component 

https://github.com/kubeflow/kubeflow/commit/b98254ea9c920da95cc64a17ced92df64a2c29a6 

.github/workflows/build-centraldashboard.yml 

Sep 1 Merge pull request #19 from StatCan/18-build-centraldashboard-component 

https://github.com/kubeflow/kubeflow/commit/18240ca1749d417e726e09f39195b580c60b45a6 

.github/workflows/build-centraldashboard.yml 

.github/workflows/build.yml 

.github/workflows/triage_issues.yaml 

Sep 1 chore(fonts): move into service 

https://github.com/kubeflow/kubeflow/commit/9bf5d6ed9e36ce8390458a8cc9d276491fbd747d 

components/centraldashboard/package-lock.json 

Many font files 

Components/centraldashboard/webpack.config.js 

Sep 1 Merge pull request #13 from StatCan/fonts-as-assets 

https://github.com/kubeflow/kubeflow/commit/7ad8eaf6bc5b99f8ef808a191773f71d08023c5b 

Sep 23 fix: rearrange dashboard cards 

https://github.com/kubeflow/kubeflow/commit/93480477a7d863d0c7d5028d49eafe0fbd330eae 

components/centraldashboard/public/components/dashboard-view.pug 

Sep 24 Merge pull request #25 from StatCan/fix-dashboard-cards 

https://github.com/kubeflow/kubeflow/commit/0831acabf69d5c6e9584a4974d46eb4e505aaf23 

Sep 28 docs:Link to own support material (***) 

https://github.com/kubeflow/kubeflow/commit/7e172902e96bef6e6ba39f7f507eb0df5f08a059 

components/centraldashboard/public/components/dashboard-view.js 

Sep 29 Merge pull request #27 from StatCan/22-link-own-docs 

https://github.com/kubeflow/kubeflow/commit/89ef76565f5ae48eeb9cb06c763dc88d4785e875 

Oct 28 fix: failing tests (!!! From the npm upgrade) 

https://github.com/kubeflow/kubeflow/commit/86e9f518a610d913f0610bd1aa54c382db99b4b5 

components/centraldashboard/app/api_workgroup.ts 

components/centraldashboard/public/ajax_test_helper.js 

components/centraldashboard/public/components/activities-list_test.js 

components/centraldashboard/public/components/registration-page.js 

Oct 28 Merge pull request #26 from StatCan/20-failing-tests 

https://github.com/kubeflow/kubeflow/commit/f8730a81796afd2041c2ffba5c9f92081db12999 

Oct 29 fix: Fix broken container scan 

https://github.com/kubeflow/kubeflow/commit/ee85c6b28a27dc74d523da7d73378857ce9e8f00 

.github/workflows/build-centraldashboard.yml 

Oct 29 fix: Security vulnerabilities 

https://github.com/kubeflow/kubeflow/commit/30116175161aace30ffc3b8007d194368ef9ae40 

components/centraldashboard/app/k8s_service.ts 

components/centraldashboard/app/k8s_service_test.ts 

Components/centraldashboard/package.json 

Oct 29 feat: Manage multiple profiles (FIRST COMMIT) 

https://github.com/kubeflow/kubeflow/commit/824022cbaf274ce430f7ecad6f4aec844dfdd488 

components/centraldashboard/public/components/main-page.js 

components/centraldashboard/public/components/main-page.pug 

components/centraldashboard/public/components/manage-users-view.js 

components/centraldashboard/public/components/manage-users-view.pug 

Oct 29 Merge pull request #28 from StatCan/fix-ci 

https://github.com/kubeflow/kubeflow/commit/8fdce6ddcc1bd87e20454b04078486a41956a82f 

Oct 30 fix: add 'ws' module to package.json 

https://github.com/kubeflow/kubeflow/commit/45d82a0b9dc2433be2edf25d90c7d26ea0390f18 

Components/centraldashboard/package.json 

Nov 2 Merge pull request #29 from StatCan/fix-centraldashboard-fails 

https://github.com/kubeflow/kubeflow/commit/3e8c3f59efac4f74fa7c0180586603e5bebdb63d 

Nov 10 feat: Manage multiple profiles 

https://github.com/kubeflow/kubeflow/commit/0ec314950388f733e84060a87d2e3eda093e6d85 

components/centraldashboard/public/components/main-page.pug 

components/centraldashboard/public/components/manage-users-view-contributorX4 

components/centraldashboard/public/components/manage-users-view.css 

components/centraldashboard/public/components/manage-users-view.js 

components/centraldashboard/public/components/manage-users-view.pug 

components/centraldashboard/public/components/manage-users-view_test.js 

Nov 12 Merge pull request #24 from StatCan/stc-manage-multiple-profiles-wip 

https://github.com/kubeflow/kubeflow/commit/0e8fa86c736e8889270a2c4040e9c7bcf19c0fa 

Nov 17 feat(centraldashboard):Official Languages 

https://github.com/kubeflow/kubeflow/commit/f85a597e5040ab518b44da81b7582d5c0252f492 

Components/centraldashboard/package.json 

Components/centraldashboard/public/assets/i18n/languages.json 

components/centraldashboard/public/components/localization-mixin.js 

And all the front end files 

components/centraldashboard/public/components/registration-page_test.js 

Nov 17 Merge pull request #31 from StatCan/stc-polymer-localize-behavior 

https://github.com/kubeflow/kubeflow/commit/cb2964cb4f5562b60c97f89b7ee79e4cb179216a 

Nov 25 fix(centraldashboard): i18n english text and french youtube link 

https://github.com/kubeflow/kubeflow/commit/0afb3f7a76cdd2f64de085db7563614ece0de22e 

Components/centraldashboard/public/assets/i18n/languages.json 

Nov 26 Merge pull request #32 from StatCan/fix-central-dashboard-i18n 

https://github.com/kubeflow/kubeflow/commit/3577e1e2d73d635940c170f936000610a69690e8

**Comment by saffaalvi** [comment]
### Kubeflow Upstream Changes 
**Central Dashboard Jan 25 – Nov 17** 
**https://github.com/kubeflow/kubeflow/compare/v1.0-branch...kubeflow:v1.2-branch** 

- Feb 3: Added a root level `healthz` api call for liveness checks. 

   - https://github.com/kubeflow/kubeflow/commit/e0d7b2edd3df2ee4c06d59d2cf59bcaa2326fcfd 

   - Components/centraldashboard/app/server.ts 

- Feb 6: [CentralDashboard][Licenses] Pushed license_info.csv file 

   - https://github.com/kubeflow/kubeflow/commit/0cb184ad15540c6d3b6b3873a210690c1eac51f1 

   - components/centraldashboard/third_party/license.txt 

   - components/centraldashboard/third_party/license_info.csv 

- Feb 25: [CentralDashboard][Testing] End-to-end testing added 

   - https://github.com/kubeflow/kubeflow/commit/f39279c02c83b875b19c85676f327cac410713a8 

   - components/centraldashboard/app/api_workgroup.ts 

   - components/centraldashboard/package-lock.json 

   - components/centraldashboard/package.json 

   - components/centraldashboard/test/.jasmine.json 

   - components/centraldashboard/test/README.md 

   - components/centraldashboard/test/e2e.test.ts 

- Mar 3: Fix dashboard wrong katib hyperlink name 

   - https://github.com/kubeflow/kubeflow/commit/29451b634cb70e7abafc9e0d3098aa02071345f3 

   - components/centraldashboard/public/components/dashboard-view.js 

- Mar 17: Fixed critical bug in identity headers isolation that broke profile-kfam response. 

   - https://github.com/kubeflow/kubeflow/commit/6503bda515928901b9e95e7dd268e00adb093533 

   - components/centraldashboard/app/api_workgroup.ts 

   - components/centraldashboard/app/attach_user_middleware.ts 

   - components/centraldashboard/test/e2e.test.ts 

- Mar 24: There should be no delay on registration flow retry if an error comes back early 

   - https://github.com/kubeflow/kubeflow/commit/3cc31748f9a9ee5648358502c9d2a7bff84b5a09 

   - components/centraldashboard/public/components/registration-page.js 

- Jun 24: env driven registration flow via REGISTRATION_FLOW 

   - https://github.com/kubeflow/kubeflow/commit/1e0cf04bc1146f02a4ebce067fd120c61ffd0583 

   - components/centraldashboard/app/api_workgroup.ts 

   - components/centraldashboard/app/api_workgroup_test.ts 

   - components/centraldashboard/app/server.ts 

   - components/centraldashboard/public/components/main-page.js 

   - components/centraldashboard/public/components/main-page_test.js 

- Jul 22: Adding reviewer to centraldashboard OWNERS file 

   - https://github.com/kubeflow/kubeflow/commit/d601b2d0d3efaddffc9d6655fe725318788bdf19 

   - components/centraldashboard/OWNERS 

- Jul 24: Rendering centraldashboard links from a configmap 

   - https://github.com/kubeflow/kubeflow/commit/ec7e01a28bf5339f784fdfddcb7bb0bcb46ce352 

   - components/centraldashboard/app/api.ts 

   - components/centraldashboard/app/k8s_service.ts 

   - components/centraldashboard/config/centraldashboard-links-config.yaml 

   - components/centraldashboard/public/components/dashboard-view.js 

   - components/centraldashboard/public/components/main-page.js 

   - components/centraldashboard/public/components/main-page.pug 

   - components/centraldashboard/public/components/main-page_test.js 

- Jul 24: Add StefanoFioravanzo to Centraldashboard OWNERS 

   - https://github.com/kubeflow/kubeflow/commit/0360d956a02970c0aae27bce591d34d903ce2d88 

   - components/centraldashboard/OWNERS 

- Aug 4: logout on Central dashboard 

   - https://github.com/kubeflow/kubeflow/commit/ed10ee2b9f1139d0f4484ed827558c7474e145a3 

   - components/centraldashboard/public/assets/icons/logout.svg 

   - components/centraldashboard/public/components/main-page.css 

   - components/centraldashboard/public/components/main-page.js 

   - components/centraldashboard/public/components/main-page.pug 

   - components/centraldashboard/public/components/main-page_test.js 

- Aug 5: Bumping central dashboard node version to v12.18.3 

   - https://github.com/kubeflow/kubeflow/commit/8097cfeb99d539ea745322273336ffecedca48d8 

   - components/centraldashboard/Dockerfile 

- Nov 3: centraldashboard: Update OWNERS file 

   - https://github.com/kubeflow/kubeflow/commit/c26282452e69bb819deedefe0498898ad5663f27 

   - components/centraldashboard/OWNERS 

- Nov 4: Merge pull request #5382 from yanniszark/feature-update-owners 

   - https://github.com/kubeflow/kubeflow/commit/0434455bf4748afa4cebb922b809dfcbbd8299a5 

   - components/centraldashboard/OWNERS 

- Nov 17: Automated cherry pick of #5404: Remove metadata link from centraldashboard 

   - https://github.com/kubeflow/kubeflow/commit/fa1bcb947a3ca0edab0a9b095c8434bfff157dbb 

   - components/centraldashboard/config/centraldashboard-links-config.yaml 

_Problematic commit (?):_ 

- Aug 28: Create an Angular Library with common frontend code 

   - https://github.com/kubeflow/kubeflow/commit/523c02b6508761aedc5913116ac6afc3dc170b14#diff-7fbb2522839a182f69809f8ddb638a514819aa0d8e8a31bf36fdad2c29d0ae96 

   - components/crud-web-apps/common/frontend/kubeflow-common-lib/projects/kubeflow/src/lib/services/namespace.service.ts 

   - Crud web app uses to talk to central dashboard for namespace selection
