### ISSUE TITLE
Compare jupyter-api changes up until v1.2

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow#38]
Issue to track down which changes and new features were made to the jupyter-web-app component up until the v1.2 release. Tracking both upstream and our changes in this issue.
Note: There is also Crud-web-apps

**Comment by saffaalvi** [comment]
This issue can be a start to tracking down changes https://github.com/StatCan/jupyter-apis/issues/42

**Comment by wg102** [comment]
Commits that were done to our Jupyter-api repo

Aug 10: 
- feat(initial): Initial commit X2 

- feat(notebooks): Add initial support for creating and delete notebooks 

- chore(notebooks): Code linting 

Aug 11: 

 adds all features 

 - fix(http): Set Content-Type on response 

 - feat(notebooks): Add volume and GPU support on Notebook creation 

 - feat(listers): Switch to informers + listers to reduce the number of … … 

 - feat(config): Add config 

 - feat(frontend): Add jupyter frontend 

 - chore(license): Add frontend license 

Aug 12: 

- feat(notebooks): Display CPU limits as a decimal 

- feat(configurations): Add configurations to the notebooks 

Aug 13: 

- feat(namespaces): Add namespaces response 

- feat(response): Update error responses to HTTP 200 because the web in… … 

Aug 14: 

- fix(notebooks): Return index.html when the new page is requested 

Aug 16: 

- feat(ci): Automate build and publish 

- feat(ci): Temporarily set back container 

- feat(ci): Automate build and publish 

Aug 19: 

- fix(npm): fix vulnerabilities (squashed commit) 

- fix: Update from deprecated font-awesome usage 

- feat: Improve local dev setup … 

- refactor: Remove unneeded statements, unreachable code 

Aug 21: 

- chore: Unset executable flag on front-end files 

- fix: angular mat-form-fiel error 

- fix: kubeflow collision 

Aug 26:  

- fix: limit local dev deployment 

- chore(fonts): add fonts as assets 

Sep 1: 

- chore(fonts): add fonts to service 

Sept 14: 

- fix(Dockerfile): add env variable 

Sept 15: 

- fix: notebook server validation 

Sept 16: 

- fix: Gi for RAM not optional 

Sept 17: 

- fix: delete old notebooks (pvc) 

Sept 23: 

- fix: resolve dependabot alerts … 

- feat: Add icons to main tables + refactor … 

Sept 24:  

- fix: browser console ExpressionChanged error 

Oct 2: 

- fix: Add status to pvc table + refactor 

Oct 6: 

- feat: Convey more info via volume status column … 

- feat: add cost estimate table 

Oct 7: 

- fix: Improve spacing for new data volume config … 

Oct 13: 

- Add message when shoose image 

- use Prettier 

21 oct: 

- fix: update ram limits 

Nov 4: 

- feat: Add Official Languages with ngx-translate * i18n 

Nov 6: 

- fix: add check for kubecost error response + translation * i18n 

Nov 10: 

- fix: kubecost table message * i18n

**Comment by wg102** [comment]
The five commits we might want upstream, with whichever additional fixes were done on them afterwards:

- Aug 19 : fix(npm): fix vulnerabilities (squashed commit) 
- Aug 26 and Sep 1: chore(fonts): add fonts as assets 
                                 chore(fonts): add fonts to service 
- Sept 17: fix: delete old notebooks (pvc) 
- Oct 6 : feat: add cost estimate table
- Nov 4: feat: Add Official Languages with ngx-translate
