### ISSUE TITLE
Update profile-controller to use Istio v1beta1 security policy APIs

### ISSUE THREAD

**Issue by justbert** [StatCan/kubeflow#43]
/kind feature

**Why you need this feature:**
Currently, the profile-controller uses v1alpha1 security policy APIs to use Istio to implement some security features. Unfortunately, [v1beta1 APIs were introduced in Istio 1.5](https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/#authentication-policy) and the [v1alpha1 APIs are no longer used as of Istio 1.6](https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/#support-ended-for-v1alpha1-security-policy).

**Describe the solution you'd like:**
The profile-controller needs to be updated to be able to continue working with Istio 1.6+, hopefully, without breaking previous functionality. 

It should be able to identify the APIs available in the cluster and instantiate the appropriate objects or allow the configuration of which to use. 

The profile-controller should also clean-up old objects that it owns if updating to newer APIs.

**Anything else you would like to add:**

**Comment by justbert** [comment]
I believe some work has started in kubeflow/kubeflow#5393.

**Comment by DavidSpek** [comment]
This should be implemented in Kubeflow 1.3. Also related is https://github.com/kubeflow/kubeflow/pull/5439. For pipelines there is https://github.com/kubeflow/manifests/pull/1719, which will receive a second part update to move to `networking.istio.io/v1beta1` from `networking.istio.io/v1alpha3` once Istio that is shipped with Anthos is updated. However, `networking.istio.io/v1alpha3` is still available in Istio 1.8 so it shouldn't be a large issue.

**Comment by justbert** [comment]
Thanks for the update @DavidSpek!

**Comment by justbert** [comment]
This seems to be done in Kubeflow 1.3
https://github.com/kubeflow/manifests/tree/v1.3.0#istio
