### ISSUE TITLE
Implement Official Languages with Angular ngx upstream

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow#49]
Our jupyter web app component now supports both English and French. 

The commits related to this feature that need to be integrated into upstream code are:
- Nov 4: feat: Add Official Languages with ngx-translate (StatCan/jupyter-apis@2e213ec)  
- ~~Jan 21: feat: Add Env variable to set language of the notebook server (StatCan/jupyter-apis@83af673)~~ A different issue was created. 

The merged PR for this issue into our code is here: https://github.com/StatCan/jupyter-apis/pull/35

**Comment by wg102** [comment]
A PR (draft) has been created https://github.com/kubeflow/kubeflow/pull/5880 to get some feedback. The PR still has some work to be done, and will not be merged before the angular update.

**Comment by wg102** [comment]
Once the PR is created and valid (not draft), a new issue will be created to track that PR and tagged with triage/blocked-upstream

**Comment by wg102** [comment]
Draft status removed and related issue https://github.com/StatCan/kubeflow/issues/56 created
