### ISSUE TITLE
Implement moving fonts into the service upstream

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow#50]
We added all fonts used as assets into the service so issues with external services don't affect ours. We've experienced some issues with page load being blocked, since it was waiting on fonts.gstatic.com.

The commits related to this feature that need to be integrated into upstream code are:
- Aug 26: chore(fonts): add fonts as assets (StatCan/jupyter-apis@2a1317b)
- Sep 1: chore(fonts): add fonts to service (StatCan/jupyter-apis@e9c0fdb)

**Comment by saffaalvi** [comment]
Created a PR upstream to implement this feature. This issue will be closed if/when they decide to merge it in.

**Comment by wg102** [comment]
Has been merged upstream
