### ISSUE TITLE
Implement the Language Env Variable

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow#55]
This issue use to be part of https://github.com/StatCan/kubeflow/issues/49 but was separated for easier tracking. 

The commits related to this feature that need to be integrated into upstream code are:
- Jan 21: feat: Add Env variable to set language of the notebook server (StatCan/jupyter-apis@83af673)

This issue is for the process of creating the PR upstream. 
It will be needed to create the python equivalent of our go code modification. 
Another issue should then be created to keep track of that PR until it is merged upstream.

**Comment by rohank07** [comment]
Translate literals using i18n localize (approach by kubeflow) and make sure it works in sync with KFLANG.
