### ISSUE TITLE
Fix npm vulnerabilities

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#8]
Fix issues reported by `npm audit` of `jupyter-web-app` component.

**Comment by saffaalvi** [comment]
Created a new branch: https://github.com/StatCan/kubeflow/tree/try-npm-fix to solve these vulnerabilities.
I am still unable to fully test these changes so did not create a PR for this issue yet either.

**Comment by brendangadd** [comment]
Closing as duplicate of StatCan/jupyter-apis#1.
